wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.11.0
      8:
      - 5
batch_size:
  desc: null
  value: 256
context_size:
  desc: null
  value: 2
embedding_size:
  desc: null
  value: 20
epochs:
  desc: null
  value: 300
learning_rate:
  desc: null
  value: 0.001
path:
  desc: null
  value: ./experiments
